export const defaultConfiguration = {
  title: "Channel Name",
  description: "Channel Desc",
  brandColors: {
    primary: "#3498db",
    primaryBackground: "#2c3e50",
  },
  sections: {
    Hero: {
      included: true,
      position: 1,
      content: {
        title: "Welcome to My Channel",
        subtitle: "Enjoy the Best Content",
        subscribeBtn: true,
        showSubscriberCount: true,
        showVideoCount: true,
      },
    },
    Videos: {
      included: true,
      position: 2,
      title: "Latest Videos",
      cardOptions: {
        showTitle: true,
        showDesc: true,
        showDate: true,
        columns: 3,
        shadow: true,
        rounded: true,
        gap: 1,
        paddingTop: 1.5,
        paddingBottom: 1.5,
        backgroundColor: "#ecf0f1",
      },
    },
    //   Playlists: {
    //     included: true,
    //     position: 3,
    //     title: "Featured Playlists",
    //     cardOptions: {
    //       showTitle: true,
    //       showDesc: true,
    //       showDate: false,
    //       columns: 3,
    //       shadow: true,
    //       rounded: true,
    //       gap: 1,
    //       paddingTop: 1.5,
    //       paddingBottom: 1.5,
    //       backgroundColor: "#ecf0f1",
    //     },
    //   },
    //   Lives: {
    //     included: true,
    //     position: 4,
    //     title: "Live Streams",
    //     cardOptions: {
    //       showTitle: true,
    //       showDesc: true,
    //       showDate: true,
    //       columns: 3,
    //       shadow: true,
    //       rounded: true,
    //       gap: 1,
    //       paddingTop: 1.5,
    //       paddingBottom: 1.5,
    //       backgroundColor: "#ecf0f1",
    //     },
    //   },
    //   Shorts: {
    //     included: true,
    //     position: 5,
    //     title: "YouTube Shorts",
    //     cardOptions: {
    //       showTitle: true,
    //       showDesc: true,
    //       showDate: true,
    //       columns: 3,
    //       shadow: true,
    //       rounded: true,
    //       gap: 1,
    //       paddingTop: 1.5,
    //       paddingBottom: 1.5,
    //       backgroundColor: "#ecf0f1",
    //     },
    //   },
    //   Posts: {
    //     included: true,
    //     position: 6,
    //     title: "Community Posts",
    //     cardOptions: {
    //       showTitle: true,
    //       showDesc: true,
    //       showDate: true,
    //       columns: 3,
    //       shadow: true,
    //       rounded: true,
    //       gap: 1,
    //       paddingTop: 1.5,
    //       paddingBottom: 1.5,
    //       backgroundColor: "#ecf0f1",
    //     },
    //   },
    Contact: {
      included: true,
      position: 7,
      content: {
        email: "contact@example.com",
        title: "Contact Me",
      },
    },
    About: {
      included: true,
      position: 8,
      content: {
        title: "About Me",
        info: "A brief introduction about the channel owner.",
      },
    },
  },
  // socialLinks: {
  //   youtube: "https://youtube.com",
  //   twitter: "https://twitter.com",
  //   instagram: "instagr",
  //   facebook: "faceboo",
  //   tiktok: "tiktok:",
  //   discord: "discord",
  //   twitch: "twitch:",
  //   linkedin: "linkedi",
  //   github: "github:",
  //   website: "website",
  // },
  socialLink: [
    {
      type: "youtube",
      link: "https://youtube.com",
    },
    {
      type: "twitter",
      link: "https://x.com",
    },
    {
      type: "instagram",
      link: "https://instagram.com",
    },
    {
      type: "facebook",
      link: "https://facebook.com",
    },
    {
      type: "tiktok",
      link: "https://tiktok.com",
    },
    {
      type: "discord",
      link: "https://discord.com",
    },
    {
      type: "twitch",
      link: "https://twitch.com",
    },
    {
      type: "linkedin",
      link: "https://linkedin.com",
    },
    {
      type: "github",
      link: "https://github.com",
    },
    {
      type: "website",
      link: "https://website.com",
    },
  ],
  showSocialShareButtons: true,
  metaTitle: "My YouTube Channel Website",
  metaDescription: "Official website for my YouTube channel.",
  metaKeywords: ["youtube", "channel", "videos", "content"],
  theme: "dark",
};