export const config = {
  APPWRITE_PROJECT_ID: process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!,
  APPWRITE_ENDPOINT: process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!,
  APPWRITE_DATABASE_ID: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!,
  APPWRITE_TABLE_ID: process.env.NEXT_PUBLIC_APPWRITE_TABLE_ID!,
  APPWRITE_API_KEY: process.env.NEXT_SECRET_APPWRITE_API_KEY!,
  GEMINI_KEY: process.env.GEMINI_API_KEY!,
};
